aajanki/yle-dl

yle-dl

As radio series like 'Lasten kuunnelmat' do not have subtitles they aren't being downloaded as an assumption is made that all series are under http://areena.yle.fi/tv/ path. By limiting subtitle search for video clips only the radio episodes are downloaded as well.

Episodes of radio series weren't being loaded

---

yle-dl

Trial period seems to be over as it's now the default
and the old areena can now be found from areena-v3.

Fix areena urls as the 'kokeilu' is now the default

---

yle-dl

The new Areena uses these formats in Elävä Arkisto:
* http://areena.yle.fi/26-<meta_id>
* http://arenan.yle.fi/26-<meta_id>
yle-dl incorrectly processes the URLs with Areena2014Downloader, which
fails with HTTP 404 error. The commit fixes this by returning
ElavaArkistoDownloader in downloader_factory for the new URLs.

Recognize new Elävä Arkisto URLs.

---

Makefile

The current Makefile BINDIR and DATADIR have an extra '/' even for the default prefix value (i.e. BINDIR expands to //usr/local/bin and DATADIR to //usr/local/share/yle-dl). The first commit makes fixes this.
The second commit sets DATADIR to be deleted when `make uninstall` is called.

Fix BINDIR and DATADIR paths, uninstall $(DATADIR)

---

.travis.yml
yle-dl

Test for errors on Travis CI.
This runs pyflakes, which checks for things like syntax errors. If any are found, the build fails. I've fixed the problems it found, except for Python 3.2 (see below).
It also runs pep8 for things like style suggestions, but won't fail the build if any are found (a lot are found).
This gives a build report like this:
https://travis-ci.org/hugovk/yle-dl/builds/105906093
It's also run for each PR, so you can see if there's problems before merging.
Python 3.2 is allowed to fail because it's failing due to `u()` which isn't in 3.2. It could be worked around, but is Python 3.2 you'd like to support?
TODO Please enable the aajanki/yle-dl repo at https://travis-ci.org/profile , it's free for open source.

Test for errors on Travis CI

---

yle-dl

From 150 to 36.
```
5       E111 indentation is not a multiple of four
1       E114 indentation is not a multiple of four (comment)
9       E127 continuation line over-indented for visual indent
1       E128 continuation line under-indented for visual indent
2       E131 continuation line unaligned for hanging indent
66      E231 missing whitespace after ','
1       E261 at least two spaces before inline comment
14      E266 too many leading '#' for block comment
12      E302 expected 2 blank lines, found 1
1       E303 too many blank lines (2)
33      E501 line too long (111 > 79 characters)
2       E502 the backslash is redundant between brackets
1       E713 test for membership should be 'not in'
2       W601 .has_key() is deprecated, use 'in'
150
```
```
1       E131 continuation line …
```

Fix some pep8 warnings

---

yle-dl

See https://github.com/rg3/youtube-dl/issues/402#issuecomment-218187016.

Youtube-dl support SOCKS proxies since 2016.05.10

---

.travis.yml

Let's use the CI to check yle-dl can be installed and run, at least with a `yle-dl --help`.
PyPy is removed because it would need more work to set up the dependencies.

Test install and yle-dl --help on CI

---

.travis.yml

Currently the CI is very slow when installing lxml because it's building from source.
This can be improved by pip installing from a prebuilt wheel.
Before, the build took **3 min 53 sec**, with `python setup.py install` taking _146.74s_.
https://travis-ci.org/hugovk/yle-dl/builds/294484376#L515
After, the build took **2 min 25 sec**, with `python setup.py install` taking _37.94s_ and `pip install lxml` taking _2.43s_.
https://travis-ci.org/hugovk/yle-dl/builds/294595373#L517

Speed up CI install of lxml: 146s -> 40s

---

setup.py

[ConfigArgParse 0.14.0](https://github.com/bw2/ConfigArgParse/releases/tag/0.14.0) was released recently and yle-dl works fine with it.

Allow ConfigArgParse > 0.13.0

---

yledl/AdobeHDS.php

Hi, I've changed a PHP keyword to comply with [this standard](https://www.php-fig.org/psr/psr-2/#25-keywords-and-truefalsenull) in PSR2. It's admittedly a small fix but I hope it helps!

Change PHP keywords to comply with PSR2

---

.travis.yml
setup.py
yledl/timestamp.py

* Add `python_requires` to help pip
* Compare version as `>= 3` instead of `== 3` to prevent surprises with any future Python 4.0
* Test on Python 3.8 beta to avoid surprises
* `sudo` no longer needed for Travis https://blog.travis-ci.com/2018-11-19-required-linux-infrastructure-migration

Version updates

---

setup.py

This will prevent a warning when running pip.
---
The reason for the upper limit is (https://github.com/aajanki/yle-dl/issues/163#issuecomment-418457066):
> The dependency is versioned, because attrs API changes every few versions, and yle-dl can only depend on a version that I know to be compatible.
And:
> The API changes also between minor versions.
However, the attrs project now promises not to break compatibility:
> attrs has a very strong backward compatibility policy that is inspired by the policy of the Twisted framework.
>
> Put simply, you shouldn’t ever be afraid to upgrade attrs if you’re only using its public APIs. If there will ever be a need to break compatibility, it will be announced in the Changelog and raise a `DeprecationWarning` for a year (if possible) before it’s …

Update setup.py to allow newest attrs

---

OS-install-instructions.md

The -dev packages have been merged into their main packages. See https://wiki.termux.com/wiki/No_more_-dev_packages

Termux does not have -dev packages anymore

---

tests/test_downloader.py
yledl/extractors.py
yledl/subtitles.py

These changes modify the output of --showmetadata option to add the stream URL for each flavor and a 'subtitles' key with language code and an URL for each available subtitle.
This makes it easier for other tools to download streams and subs from Areena. An extractor for youtube-dl using the output is here: https://github.com/tpikonen/youtube-dl/tree/yledl

Add stream and subtitle URLs to metadata

---

yledl/backends.py

Add support for downloading video data through a HTTP proxy with HLS streams.
Proxy is passed to ffmpeg by `-http_proxy` command line option.
Also use specified proxy with external subtitles in wget backend.

Proxy improvements

---

yledl/backends.py
yledl/config.py
yledl/http.py
yledl/yledl.py

This implements the basic region restriction bypass that @eevvoor mentioned in #267. A random IP address from an Elisa subnet identified by the youtube-dl developers is chosen, and that IP address is added to a new `X-Forwarded-For` header in `yledl_headers()` and as an argument to `ffmpeg`. This allowed me to successfully download [a Rölli episode](https://areena.yle.fi/1-736890) that is only available in Finland.
The `--geoblocked` tests are still failing even with these changes in place. I believe that this is because those tests only test live TV streams which probably do not have the new header yet. I am currently unsure of where else the `X-Forwarded-For` header should be added to handle these tests and other content. I will continue working on this, but I would appreciate any …

Added X-Forwarded-For header to bypass region restrictions

---

yledl/backends.py

This allows users to bypass geographic restrictions when using wget backend (PR #283 already added bypass to HLS backend).

Add geographic restriction bypass to wget backend

---

yledl/titleformatter.py
yledl/yledl.py

The extra automatic separators inserted in the output template have been removed as described in #280. The default output template has been changed to match the original, but some cases do not match now if an argument does not exist. This is causing most of the title formatter tests and some of the downloading tests to fail. I tested the video in #280, and it downloads successfully with multiple different output templates.

Removed automatic separators in output template

---

yledl/downloader.py
yledl/io.py
yledl/titleformatter.py
yledl/yledl.py

This allows to specify subdirectories with the output template definition using
'/'.  Nested subdirectories are also supported. A flag `--create-dirs`
is added to automatically create missing directories.
For example: `--output-template '${series}/${title} --create-dirs` will store
files as `${title}` to subdirectories defined by the `${series}` metadata.

Output template with subdirectory

---

setup.py
tests/integration/test_arkivet_it.py
tests/test_downloader.py
tests/test_flavor_filters.py
tests/test_timestamp.py
yledl/backends.py
yledl/downloader.py
yledl/exitcodes.py
yledl/extractors.py
yledl/ffprobe.py
yledl/geolocation.py
yledl/http.py
yledl/io.py
yledl/jsonhelpers.py
yledl/kaltura.py
yledl/localization.py
yledl/streamfilters.py
yledl/streamflavor.py
yledl/streamprobe.py
yledl/subtitles.py
yledl/timestamp.py
yledl/titleformatter.py
yledl/utils.py
yledl/yledl.py

Since yle-dl is Python 3.6+ only, we can modernize a thing or two:
This PR:
* runs `pyupgrade --py36-plus` to get rid of some vestigial py2-isms
* fixes a bunch of things pycodestyle was complaining about (by hand)
* runs `flynt` to auto-convert string formatting to f-strings
* finally, applies some manual elbow grease to fix up usages of `.format`, ` % `, ` + `, etc. to f-strings as well

Modernize code style somewhat

---

yledl/__main__.py

This allows running with
```
python -m yledl
```
instead of
```
python -m yledl.yledl
```
(which also causes a spurious `RuntimeWarning: 'yledl.yledl' found in sys.modules after import of package 'yledl', but prior to execution of 'yledl.yledl'; this may result in unpredictable behaviour`).

Add yledl/__main__.py to allow python -m yledl

---

yledl/downloader.py
yledl/io.py
yledl/titleformatter.py

I noticed a couple bugs the other day when I tried to use the `--postprocess` option.
Downloading the news with the following command (using `echo` as a placeholder postprocessing command)
```
yle-dl 'https://areena.yle.fi/1-50922783' -o uutiset --postprocess echo
```
I got the following error:
```
...
Stream saved to uutiset.mkv
ERROR: Failed to execute e c h o | u u t i s e t . m k v
ERROR: No such file or directory
```
The user provided command with the yle-dl provided arguments were passed to `Subprocess().execute()` with one level too shallow nesting. Thus the strings were treated each as a single piece of a pipeline.
---
I didn't have the latest version locally (some pre `--create-dirs` version), so once I had fixed the above, I got the following error:
```
yle-dl 20220213: Download …
```

Fix postprocess and handling of filename with no directory component

---

README.md

https://mpv.io/manual/stable/#cache
The flag `--cache=1000` doesn't exist — `--cache-secs=1000` can be used  (assuming seconds).
```
Invalid value for option cache: 1000
Valid values are:
no
auto
yes
Error parsing option cache (option parameter could not be parsed)
Setting commandline option --cache=1000 failed.
```

mpv's --cache flag

---

ChangeLog
README.fi
README.md

Most places where GPL v3 is mentioned
also already mention that any later version is also accepted.
There were just a couple of top level files where this was not explicit.
Added to avoid any unclarity about the license.
The background for this pull request is that I am attempting to package yle-dl for Fedora.
Fedora requires a license review to be conducted,
and initially README's plain "GPLv3" led me to believe the correct license if "GPL v3 only" —
but the rest of repository content indicate it is actually "or later".

Clarify license by mentioning "or later" everywhere

---

index-en.html
index-sv.html
index.html

Also changed the links to the pages in different languages to be in the given language, for example the link to the Finnish page says "Suomeksi" instead of "In Finnish", which seems more natural.

Translate webpage to Swedish

---

README.fi.md
README.md
yledl.conf.sample
yledl/yledl.py

According to the [XDG Base Directory Specification](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html), config files should be under the `$XDG_CONFIG_HOME` directory (which defaults to `~/.config`), and not directly under the home directory.
In other words, a lot of modern Linux apps have their config under `~/.config` and not directly in the home dir, which makes your home a bit neater.
There was already a list of default config paths, so this was nice and easy to add.

Search for the config file under XDG_CONFIG_HOME

---

yledl/io.py

- some Linux distributions package `ffmpeg` such that `ffmpeg`'s version number is prefixed with letter `n`
- this extra prefix `n` confuses `yle-dl`'s `ffmpeg_version` checker function and consequently subtitles fail to download (see #380)
- this PR takes the extra prefix `n` into account in the regular expression in `ffmpeg_version`
Arch Linux builds `ffmpeg` directly from [Git sources](https://gitlab.archlinux.org/archlinux/packaging/packages/ffmpeg/-/blob/1e27244932c2c61ab340b357ff4ac8dd0065e3af/PKGBUILD#L123). This means that it uses [Git tags](https://git.ffmpeg.org/gitweb/ffmpeg.git/tags) as version numbers for the binary. In other words, version numbers will have `n` prefix.
For example:
```
arch$ ffmpeg -loglevel quiet -version
ffmpeg version n7.1.1 Copyright (c) 2000-2025 the …
```

Improve FFmpeg version checker regular expression to fix subtitle downloads
